version: '3'
services:
  app:
   build: 
     context: .
     dockerfile: Dockerfile
    #image: node-mongo
    container_name: node-mongo
    restart: always
    build: .
    ports:
      - '3000:3000'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      MONGO_URL: mongodb-service
    container_name: node-app
  
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    container_name: mongodb-service
